/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import java.awt.Color;
import javax.swing.JLabel;
/**
 *
 * @author uset
 */
public class MENU_EMP extends javax.swing.JFrame {

    int xMouse, yMouse;
    public MENU_EMP() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NombreUsuario = new javax.swing.JLabel();
        CodUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EmpNuevaVenta = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        EmpClientes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EmpProductos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        EmpEmpresa = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        EmpVentas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        LabelExit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Menu2 = new javax.swing.JTabbedPane();
        MenuNUEVAVENTA = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblNV = new javax.swing.JTable();
        NVnombre = new javax.swing.JTextField();
        NVcodigo = new javax.swing.JTextField();
        NVdescripcion = new javax.swing.JTextField();
        NVcantidad = new javax.swing.JTextField();
        NVtotal = new javax.swing.JTextField();
        NVdni = new javax.swing.JTextField();
        NVprecio = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        NVstock = new javax.swing.JTextField();
        NVsubtotal = new javax.swing.JTextField();
        NVigv = new javax.swing.JTextField();
        NVcancelar = new javax.swing.JButton();
        NVagregar = new javax.swing.JButton();
        NVguardar = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        NVeliminar = new javax.swing.JButton();
        NVbuscarCL = new javax.swing.JButton();
        NVbuscarPR = new javax.swing.JButton();
        MenuCLIENTES = new javax.swing.JPanel();
        CLeliminar = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        CLnombre = new javax.swing.JTextField();
        CLapellidos = new javax.swing.JTextField();
        CLdni = new javax.swing.JTextField();
        BuscProducto2 = new javax.swing.JLabel();
        BuscProducto3 = new javax.swing.JLabel();
        BuscProducto4 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        CLeditar = new javax.swing.JButton();
        CLguardar = new javax.swing.JButton();
        CLagregar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtblCL = new javax.swing.JTable();
        BuscarCL = new javax.swing.JButton();
        CLbuscador = new javax.swing.JTextField();
        eliminarBuscarCL = new javax.swing.JButton();
        ReporteExcelCL = new javax.swing.JButton();
        MenuPRODUCTOS = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblPR = new javax.swing.JTable();
        BuscarPR = new javax.swing.JButton();
        PRbuscador = new javax.swing.JTextField();
        eliminarBuscarPR = new javax.swing.JButton();
        MenuEMPRESA = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        telefonoEmpresa = new javax.swing.JLabel();
        nombreEmpresa = new javax.swing.JLabel();
        rucEmpresa = new javax.swing.JLabel();
        direccionEmpresa = new javax.swing.JLabel();
        razonEmpresa = new javax.swing.JLabel();
        MenuREPORTEVENTAS = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtblVENTAS = new javax.swing.JTable();
        PDFventas = new javax.swing.JButton();
        JCalendar = new com.toedter.calendar.JDateChooser();
        BuscarFechaVenta = new javax.swing.JButton();
        LimpiarBusqueda = new javax.swing.JButton();
        ReporteExcelVENTAS = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 192, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 850));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreUsuario.setFont(new java.awt.Font("Corbel Light", 0, 24)); // NOI18N
        NombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        NombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 260, 50));

        CodUsuario.setFont(new java.awt.Font("Corbel Light", 0, 24)); // NOI18N
        CodUsuario.setForeground(new java.awt.Color(255, 255, 255));
        CodUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(CodUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/EMPLOGO.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 170));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Empleado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 260, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FONDOM(1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 300));

        EmpNuevaVenta.setBackground(new java.awt.Color(229, 192, 144));
        EmpNuevaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpNuevaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpNuevaVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpNuevaVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpNuevaVentaMouseExited(evt);
            }
        });
        EmpNuevaVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nueva venta");
        EmpNuevaVenta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 180, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/carrito-de-compras(2).png"))); // NOI18N
        EmpNuevaVenta.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 70));

        jPanel1.add(EmpNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 260, 70));

        EmpClientes.setBackground(new java.awt.Color(229, 192, 144));
        EmpClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpClientesMouseExited(evt);
            }
        });
        EmpClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clientes");
        EmpClientes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 180, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CLIENTES.png"))); // NOI18N
        EmpClientes.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 70));

        jPanel1.add(EmpClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 260, 70));

        EmpProductos.setBackground(new java.awt.Color(229, 192, 144));
        EmpProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpProductosMouseExited(evt);
            }
        });
        EmpProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Productos");
        EmpProductos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 180, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/menu.png"))); // NOI18N
        EmpProductos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 70));

        jPanel1.add(EmpProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 260, 70));

        EmpEmpresa.setBackground(new java.awt.Color(229, 192, 144));
        EmpEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpEmpresaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpEmpresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpEmpresaMouseExited(evt);
            }
        });
        EmpEmpresa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Empresa");
        EmpEmpresa.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 180, 70));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/EMPRESA.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        EmpEmpresa.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 70));

        jPanel1.add(EmpEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 260, 70));

        EmpVentas.setBackground(new java.awt.Color(229, 192, 144));
        EmpVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpVentasMouseExited(evt);
            }
        });
        EmpVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ventas");
        EmpVentas.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 180, 70));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/reporte.png"))); // NOI18N
        EmpVentas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 70));

        jPanel1.add(EmpVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 260, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 850));

        btnMinimizar.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setText("_");
        btnMinimizar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });
        getContentPane().add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 40, 40));

        LabelExit.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LabelExit.setForeground(new java.awt.Color(255, 255, 255));
        LabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelExit.setText("X");
        LabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelExitMouseExited(evt);
            }
        });
        getContentPane().add(LabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 40, 60));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LOGO_PIZZA.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 960, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FONDOM(3).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 960, 200));

        MenuNUEVAVENTA.setBackground(new java.awt.Color(204, 204, 204));
        MenuNUEVAVENTA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblNV.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jtblNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCIÓN", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtblNV);
        if (jtblNV.getColumnModel().getColumnCount() > 0) {
            jtblNV.getColumnModel().getColumn(0).setResizable(false);
            jtblNV.getColumnModel().getColumn(1).setResizable(false);
            jtblNV.getColumnModel().getColumn(2).setResizable(false);
            jtblNV.getColumnModel().getColumn(3).setResizable(false);
            jtblNV.getColumnModel().getColumn(4).setResizable(false);
        }

        MenuNUEVAVENTA.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 850, 380));

        NVnombre.setBackground(new java.awt.Color(204, 204, 204));
        NVnombre.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        NVnombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        MenuNUEVAVENTA.add(NVnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 210, 30));

        NVcodigo.setBackground(new java.awt.Color(204, 204, 204));
        NVcodigo.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        NVcodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        NVcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVcodigoActionPerformed(evt);
            }
        });
        MenuNUEVAVENTA.add(NVcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        NVdescripcion.setBackground(new java.awt.Color(204, 204, 204));
        NVdescripcion.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        NVdescripcion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        NVdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVdescripcionActionPerformed(evt);
            }
        });
        MenuNUEVAVENTA.add(NVdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 180, 30));

        NVcantidad.setBackground(new java.awt.Color(204, 204, 204));
        NVcantidad.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        NVcantidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        MenuNUEVAVENTA.add(NVcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 50, 30));

        NVtotal.setBackground(new java.awt.Color(204, 204, 204));
        NVtotal.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        NVtotal.setBorder(null);
        NVtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVtotalActionPerformed(evt);
            }
        });
        MenuNUEVAVENTA.add(NVtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, 90, 20));

        NVdni.setBackground(new java.awt.Color(204, 204, 204));
        NVdni.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        NVdni.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        NVdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVdniActionPerformed(evt);
            }
        });
        MenuNUEVAVENTA.add(NVdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 130, 30));

        NVprecio.setBackground(new java.awt.Color(204, 204, 204));
        NVprecio.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        NVprecio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        MenuNUEVAVENTA.add(NVprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 60, 30));

        jLabel29.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel29.setText("Nombre");
        MenuNUEVAVENTA.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 120, 30));

        jLabel33.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel33.setText("Código");
        MenuNUEVAVENTA.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        jLabel34.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel34.setText("Descripción");
        MenuNUEVAVENTA.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 90, 30));

        jLabel35.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel35.setText("Cantidad");
        MenuNUEVAVENTA.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 60, 30));

        jLabel36.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel36.setText("Precio");
        MenuNUEVAVENTA.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 50, 30));

        jLabel37.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel37.setText("Stock");
        MenuNUEVAVENTA.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 50, 30));

        jLabel38.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel38.setText("ID Cliente");
        MenuNUEVAVENTA.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 110, 30));

        jLabel39.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("TOTAL");
        MenuNUEVAVENTA.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 110, 20));

        jLabel40.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("SubTotal");
        MenuNUEVAVENTA.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 110, 20));

        jLabel41.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("IGV");
        MenuNUEVAVENTA.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 110, 20));

        NVstock.setBackground(new java.awt.Color(204, 204, 204));
        NVstock.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        NVstock.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        NVstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVstockActionPerformed(evt);
            }
        });
        MenuNUEVAVENTA.add(NVstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 60, 30));

        NVsubtotal.setBackground(new java.awt.Color(204, 204, 204));
        NVsubtotal.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        NVsubtotal.setBorder(null);
        NVsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVsubtotalActionPerformed(evt);
            }
        });
        MenuNUEVAVENTA.add(NVsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 90, 20));

        NVigv.setBackground(new java.awt.Color(204, 204, 204));
        NVigv.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        NVigv.setBorder(null);
        NVigv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVigvActionPerformed(evt);
            }
        });
        MenuNUEVAVENTA.add(NVigv, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 90, 20));

        NVcancelar.setBackground(new java.awt.Color(188, 146, 100));
        NVcancelar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        NVcancelar.setForeground(new java.awt.Color(255, 255, 255));
        NVcancelar.setText("CANCELAR");
        NVcancelar.setBorder(null);
        NVcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NVcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NVcancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NVcancelarMouseExited(evt);
            }
        });
        MenuNUEVAVENTA.add(NVcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 70, 50));

        NVagregar.setBackground(new java.awt.Color(188, 146, 100));
        NVagregar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        NVagregar.setForeground(new java.awt.Color(255, 255, 255));
        NVagregar.setText("AGREGAR");
        NVagregar.setBorder(null);
        NVagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NVagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NVagregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NVagregarMouseExited(evt);
            }
        });
        NVagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVagregarActionPerformed(evt);
            }
        });
        MenuNUEVAVENTA.add(NVagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 70, 50));

        NVguardar.setBackground(new java.awt.Color(188, 146, 100));
        NVguardar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        NVguardar.setForeground(new java.awt.Color(255, 255, 255));
        NVguardar.setText("GUARDAR");
        NVguardar.setBorder(null);
        NVguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NVguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NVguardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NVguardarMouseExited(evt);
            }
        });
        MenuNUEVAVENTA.add(NVguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 110, 50));

        jLabel42.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel42.setText("S/");
        MenuNUEVAVENTA.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 20, 20));

        jLabel43.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel43.setText("S/");
        MenuNUEVAVENTA.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 20, 20));

        jLabel44.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel44.setText("S/");
        MenuNUEVAVENTA.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 20, 20));

        NVeliminar.setBackground(new java.awt.Color(188, 146, 100));
        NVeliminar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        NVeliminar.setForeground(new java.awt.Color(255, 255, 255));
        NVeliminar.setText("ELIMINAR");
        NVeliminar.setBorder(null);
        NVeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NVeliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NVeliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NVeliminarMouseExited(evt);
            }
        });
        MenuNUEVAVENTA.add(NVeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 70, 50));

        NVbuscarCL.setBackground(new java.awt.Color(204, 204, 204));
        NVbuscarCL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/buscador(1).png"))); // NOI18N
        NVbuscarCL.setBorder(null);
        NVbuscarCL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuNUEVAVENTA.add(NVbuscarCL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, -1, -1));

        NVbuscarPR.setBackground(new java.awt.Color(204, 204, 204));
        NVbuscarPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/buscador(1).png"))); // NOI18N
        NVbuscarPR.setBorder(null);
        NVbuscarPR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuNUEVAVENTA.add(NVbuscarPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        Menu2.addTab("tab1", MenuNUEVAVENTA);

        MenuCLIENTES.setBackground(new java.awt.Color(204, 204, 204));
        MenuCLIENTES.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CLeliminar.setBackground(new java.awt.Color(204, 204, 204));
        CLeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/borrar(1).png"))); // NOI18N
        CLeliminar.setBorder(null);
        CLeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLeliminarActionPerformed(evt);
            }
        });
        MenuCLIENTES.add(CLeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 40, 40));

        jLabel45.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel45.setText("DNI");
        MenuCLIENTES.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 30));

        CLnombre.setBackground(new java.awt.Color(204, 204, 204));
        CLnombre.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        CLnombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        CLnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLnombreActionPerformed(evt);
            }
        });
        MenuCLIENTES.add(CLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 140, 30));

        CLapellidos.setBackground(new java.awt.Color(204, 204, 204));
        CLapellidos.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        CLapellidos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        CLapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLapellidosActionPerformed(evt);
            }
        });
        MenuCLIENTES.add(CLapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 140, 30));

        CLdni.setBackground(new java.awt.Color(204, 204, 204));
        CLdni.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        CLdni.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        CLdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLdniActionPerformed(evt);
            }
        });
        MenuCLIENTES.add(CLdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 120, 30));

        BuscProducto2.setBackground(new java.awt.Color(225, 194, 134));
        BuscProducto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/usuario(1).png"))); // NOI18N
        BuscProducto2.setText("jLabel28");
        BuscProducto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCLIENTES.add(BuscProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 30, 30));

        BuscProducto3.setBackground(new java.awt.Color(225, 194, 134));
        BuscProducto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/usuario(1).png"))); // NOI18N
        BuscProducto3.setText("jLabel28");
        BuscProducto3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCLIENTES.add(BuscProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 30, 30));

        BuscProducto4.setBackground(new java.awt.Color(225, 194, 134));
        BuscProducto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/tarjetas-de-identificacion.png"))); // NOI18N
        BuscProducto4.setText("jLabel28");
        BuscProducto4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCLIENTES.add(BuscProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 30, 30));

        jLabel46.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel46.setText("Nombre");
        MenuCLIENTES.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 110, 30));

        jLabel47.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel47.setText("Apellidos");
        MenuCLIENTES.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 110, 30));

        CLeditar.setBackground(new java.awt.Color(188, 146, 100));
        CLeditar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        CLeditar.setForeground(new java.awt.Color(255, 255, 255));
        CLeditar.setText("EDITAR");
        CLeditar.setBorder(null);
        CLeditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLeditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CLeditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CLeditarMouseExited(evt);
            }
        });
        CLeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLeditarActionPerformed(evt);
            }
        });
        MenuCLIENTES.add(CLeditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 70, 70));

        CLguardar.setBackground(new java.awt.Color(188, 146, 100));
        CLguardar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        CLguardar.setForeground(new java.awt.Color(255, 255, 255));
        CLguardar.setText("GUARDAR");
        CLguardar.setBorder(null);
        CLguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CLguardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CLguardarMouseExited(evt);
            }
        });
        CLguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLguardarActionPerformed(evt);
            }
        });
        MenuCLIENTES.add(CLguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 70, 70));

        CLagregar.setBackground(new java.awt.Color(188, 146, 100));
        CLagregar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        CLagregar.setForeground(new java.awt.Color(255, 255, 255));
        CLagregar.setText("AGREGAR");
        CLagregar.setBorder(null);
        CLagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CLagregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CLagregarMouseExited(evt);
            }
        });
        CLagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLagregarActionPerformed(evt);
            }
        });
        MenuCLIENTES.add(CLagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 70, 70));

        jtblCL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DNI", "NOMBRE", "APELLIDOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jtblCL);
        if (jtblCL.getColumnModel().getColumnCount() > 0) {
            jtblCL.getColumnModel().getColumn(0).setResizable(false);
            jtblCL.getColumnModel().getColumn(1).setResizable(false);
            jtblCL.getColumnModel().getColumn(2).setResizable(false);
            jtblCL.getColumnModel().getColumn(3).setResizable(false);
        }

        MenuCLIENTES.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 610, -1));

        BuscarCL.setBackground(new java.awt.Color(204, 204, 204));
        BuscarCL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/buscador(1).png"))); // NOI18N
        BuscarCL.setBorder(null);
        BuscarCL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCLIENTES.add(BuscarCL, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 35, 35));

        CLbuscador.setBackground(new java.awt.Color(204, 204, 204));
        CLbuscador.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        CLbuscador.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        CLbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLbuscadorActionPerformed(evt);
            }
        });
        MenuCLIENTES.add(CLbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 180, 30));

        eliminarBuscarCL.setBackground(new java.awt.Color(204, 204, 204));
        eliminarBuscarCL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cancelar(3).png"))); // NOI18N
        eliminarBuscarCL.setBorder(null);
        eliminarBuscarCL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCLIENTES.add(eliminarBuscarCL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 35, 35));

        ReporteExcelCL.setBackground(new java.awt.Color(204, 204, 204));
        ReporteExcelCL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/archivo-xls(1).png"))); // NOI18N
        ReporteExcelCL.setBorder(null);
        ReporteExcelCL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCLIENTES.add(ReporteExcelCL, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 40, 40));

        Menu2.addTab("tab2", MenuCLIENTES);

        MenuPRODUCTOS.setBackground(new java.awt.Color(204, 204, 204));
        MenuPRODUCTOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblPR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "PRECIO", "STOCK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtblPR);
        if (jtblPR.getColumnModel().getColumnCount() > 0) {
            jtblPR.getColumnModel().getColumn(0).setResizable(false);
            jtblPR.getColumnModel().getColumn(0).setPreferredWidth(20);
            jtblPR.getColumnModel().getColumn(1).setResizable(false);
            jtblPR.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtblPR.getColumnModel().getColumn(2).setResizable(false);
            jtblPR.getColumnModel().getColumn(2).setPreferredWidth(15);
            jtblPR.getColumnModel().getColumn(3).setResizable(false);
            jtblPR.getColumnModel().getColumn(3).setPreferredWidth(15);
        }

        MenuPRODUCTOS.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 50, 870, -1));

        BuscarPR.setBackground(new java.awt.Color(204, 204, 204));
        BuscarPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/buscador(1).png"))); // NOI18N
        BuscarPR.setBorder(null);
        BuscarPR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuPRODUCTOS.add(BuscarPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 35, 35));

        PRbuscador.setBackground(new java.awt.Color(204, 204, 204));
        PRbuscador.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        PRbuscador.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        PRbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRbuscadorActionPerformed(evt);
            }
        });
        MenuPRODUCTOS.add(PRbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 180, 30));

        eliminarBuscarPR.setBackground(new java.awt.Color(204, 204, 204));
        eliminarBuscarPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cancelar(3).png"))); // NOI18N
        eliminarBuscarPR.setBorder(null);
        eliminarBuscarPR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuPRODUCTOS.add(eliminarBuscarPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 35, 35));

        Menu2.addTab("tab3", MenuPRODUCTOS);

        MenuEMPRESA.setBackground(new java.awt.Color(204, 204, 204));
        MenuEMPRESA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("DATOS DE LA EMPRESA");
        MenuEMPRESA.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 960, 80));

        jLabel49.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel49.setText("Nombre");
        MenuEMPRESA.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, 30));

        jLabel51.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel51.setText("RUC");
        MenuEMPRESA.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 110, 30));

        jLabel52.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel52.setText("Dirección");
        MenuEMPRESA.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 110, 30));

        jLabel53.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel53.setText("Razón Social");
        MenuEMPRESA.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 110, 30));

        jLabel54.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel54.setText("Teléfono");
        MenuEMPRESA.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 110, 30));

        telefonoEmpresa.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        telefonoEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        MenuEMPRESA.add(telefonoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 210, 30));

        nombreEmpresa.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        nombreEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        MenuEMPRESA.add(nombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 210, 30));

        rucEmpresa.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        rucEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        MenuEMPRESA.add(rucEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 210, 30));

        direccionEmpresa.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        direccionEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        MenuEMPRESA.add(direccionEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 210, 30));

        razonEmpresa.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        razonEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        MenuEMPRESA.add(razonEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 250, 30));

        Menu2.addTab("tab5", MenuEMPRESA);

        MenuREPORTEVENTAS.setBackground(new java.awt.Color(204, 204, 204));
        MenuREPORTEVENTAS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblVENTAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "CLIENTES", "VENDEDOR", "SUBTOTAL", "IGV", "TOTAL", "FECHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jtblVENTAS);
        if (jtblVENTAS.getColumnModel().getColumnCount() > 0) {
            jtblVENTAS.getColumnModel().getColumn(0).setResizable(false);
            jtblVENTAS.getColumnModel().getColumn(1).setResizable(false);
            jtblVENTAS.getColumnModel().getColumn(2).setResizable(false);
            jtblVENTAS.getColumnModel().getColumn(3).setResizable(false);
            jtblVENTAS.getColumnModel().getColumn(4).setResizable(false);
            jtblVENTAS.getColumnModel().getColumn(5).setResizable(false);
            jtblVENTAS.getColumnModel().getColumn(6).setResizable(false);
        }

        MenuREPORTEVENTAS.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 910, 410));

        PDFventas.setBackground(new java.awt.Color(204, 204, 204));
        PDFventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/pdf(1).png"))); // NOI18N
        PDFventas.setBorder(null);
        PDFventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuREPORTEVENTAS.add(PDFventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 60, 60));
        MenuREPORTEVENTAS.add(JCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 30));

        BuscarFechaVenta.setBackground(new java.awt.Color(188, 146, 100));
        BuscarFechaVenta.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        BuscarFechaVenta.setForeground(new java.awt.Color(255, 255, 255));
        BuscarFechaVenta.setText("BUSCAR");
        BuscarFechaVenta.setBorder(null);
        BuscarFechaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarFechaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuscarFechaVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarFechaVentaMouseExited(evt);
            }
        });
        MenuREPORTEVENTAS.add(BuscarFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 80, 40));

        LimpiarBusqueda.setBackground(new java.awt.Color(188, 146, 100));
        LimpiarBusqueda.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        LimpiarBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        LimpiarBusqueda.setText("ELIMINAR BUSQUEDA");
        LimpiarBusqueda.setBorder(null);
        LimpiarBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LimpiarBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LimpiarBusquedaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LimpiarBusquedaMouseExited(evt);
            }
        });
        MenuREPORTEVENTAS.add(LimpiarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 160, 40));

        ReporteExcelVENTAS.setBackground(new java.awt.Color(204, 204, 204));
        ReporteExcelVENTAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/archivo-xls(1).png"))); // NOI18N
        ReporteExcelVENTAS.setBorder(null);
        ReporteExcelVENTAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuREPORTEVENTAS.add(ReporteExcelVENTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 40, 40));

        Menu2.addTab("tab6", MenuREPORTEVENTAS);

        getContentPane().add(Menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 960, 680));

        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        btnMinimizar.setForeground(Color.gray);
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        btnMinimizar.setForeground(Color.white);
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void LabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_LabelExitMouseClicked

    private void LabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseEntered
        LabelExit.setForeground(Color.red);
    }//GEN-LAST:event_LabelExitMouseEntered

    private void LabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseExited
        LabelExit.setForeground(Color.white);
    }//GEN-LAST:event_LabelExitMouseExited

    private void EmpNuevaVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpNuevaVentaMouseEntered
        EmpNuevaVenta.setBackground(new Color(200,166,117));
    }//GEN-LAST:event_EmpNuevaVentaMouseEntered

    private void EmpNuevaVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpNuevaVentaMouseExited
        EmpNuevaVenta.setBackground(new Color(229,192,144));
    }//GEN-LAST:event_EmpNuevaVentaMouseExited

    private void EmpNuevaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpNuevaVentaMouseClicked
        Menu2.setSelectedIndex(0);
    }//GEN-LAST:event_EmpNuevaVentaMouseClicked

    private void EmpClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpClientesMouseEntered
        EmpClientes.setBackground(new Color(200,166,117));
    }//GEN-LAST:event_EmpClientesMouseEntered

    private void EmpClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpClientesMouseExited
        EmpClientes.setBackground(new Color(229,192,144));
    }//GEN-LAST:event_EmpClientesMouseExited

    private void EmpClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpClientesMouseClicked
        Menu2.setSelectedIndex(1);
    }//GEN-LAST:event_EmpClientesMouseClicked

    private void EmpProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpProductosMouseEntered
        EmpProductos.setBackground(new Color(200,166,117));
    }//GEN-LAST:event_EmpProductosMouseEntered

    private void EmpProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpProductosMouseExited
        EmpProductos.setBackground(new Color(229,192,144));
    }//GEN-LAST:event_EmpProductosMouseExited

    private void EmpProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpProductosMouseClicked
        Menu2.setSelectedIndex(2);
    }//GEN-LAST:event_EmpProductosMouseClicked

    private void EmpEmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpEmpresaMouseEntered
        EmpEmpresa.setBackground(new Color(200,166,117));
    }//GEN-LAST:event_EmpEmpresaMouseEntered

    private void EmpEmpresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpEmpresaMouseExited
        EmpEmpresa.setBackground(new Color(229,192,144));
    }//GEN-LAST:event_EmpEmpresaMouseExited

    private void EmpEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpEmpresaMouseClicked
        Menu2.setSelectedIndex(3);
    }//GEN-LAST:event_EmpEmpresaMouseClicked

    private void EmpVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpVentasMouseEntered
        EmpVentas.setBackground(new Color(200,166,117));
    }//GEN-LAST:event_EmpVentasMouseEntered

    private void EmpVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpVentasMouseExited
        EmpVentas.setBackground(new Color(229,192,144));
    }//GEN-LAST:event_EmpVentasMouseExited

    private void EmpVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpVentasMouseClicked
        Menu2.setSelectedIndex(4);
    }//GEN-LAST:event_EmpVentasMouseClicked

    private void NVcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NVcodigoActionPerformed

    private void NVdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NVdescripcionActionPerformed

    private void NVtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NVtotalActionPerformed

    private void NVdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NVdniActionPerformed

    private void NVstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NVstockActionPerformed

    private void NVsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NVsubtotalActionPerformed

    private void NVigvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVigvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NVigvActionPerformed

    private void NVcancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NVcancelarMouseEntered
        NVcancelar.setBackground(new Color(225,194,134));
    }//GEN-LAST:event_NVcancelarMouseEntered

    private void NVcancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NVcancelarMouseExited
        NVcancelar.setBackground(new Color(188,146,100));
    }//GEN-LAST:event_NVcancelarMouseExited

    private void NVagregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NVagregarMouseEntered
        NVagregar.setBackground(new Color(225,194,134));
    }//GEN-LAST:event_NVagregarMouseEntered

    private void NVagregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NVagregarMouseExited
        NVagregar.setBackground(new Color(188,146,100));
    }//GEN-LAST:event_NVagregarMouseExited

    private void NVagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVagregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NVagregarActionPerformed

    private void NVguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NVguardarMouseEntered
        NVguardar.setBackground(new Color(225,194,134));
    }//GEN-LAST:event_NVguardarMouseEntered

    private void NVguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NVguardarMouseExited
        NVguardar.setBackground(new Color(188,146,100));
    }//GEN-LAST:event_NVguardarMouseExited

    private void CLnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLnombreActionPerformed

    private void CLapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLapellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLapellidosActionPerformed

    private void CLdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLdniActionPerformed

    private void CLeditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLeditarMouseEntered
        CLeditar.setBackground(new Color(225,194,134));
    }//GEN-LAST:event_CLeditarMouseEntered

    private void CLeditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLeditarMouseExited
        CLeditar.setBackground(new Color(188,146,100));
    }//GEN-LAST:event_CLeditarMouseExited

    private void CLeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLeditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLeditarActionPerformed

    private void CLguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLguardarMouseEntered
        CLguardar.setBackground(new Color(225,194,134));
    }//GEN-LAST:event_CLguardarMouseEntered

    private void CLguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLguardarMouseExited
        CLguardar.setBackground(new Color(188,146,100));
    }//GEN-LAST:event_CLguardarMouseExited

    private void CLguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLguardarActionPerformed

    private void CLagregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLagregarMouseEntered
        CLagregar.setBackground(new Color(225,194,134));
    }//GEN-LAST:event_CLagregarMouseEntered

    private void CLagregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLagregarMouseExited
        CLagregar.setBackground(new Color(188,146,100));
    }//GEN-LAST:event_CLagregarMouseExited

    private void CLagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLagregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLagregarActionPerformed

    private void NVeliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NVeliminarMouseEntered
        NVeliminar.setBackground(new Color(225,194,134));
    }//GEN-LAST:event_NVeliminarMouseEntered

    private void NVeliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NVeliminarMouseExited
        NVeliminar.setBackground(new Color(188,146,100));
    }//GEN-LAST:event_NVeliminarMouseExited

    private void CLbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLbuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLbuscadorActionPerformed

    private void PRbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRbuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRbuscadorActionPerformed

    private void BuscarFechaVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarFechaVentaMouseEntered
        BuscarFechaVenta.setBackground(new Color(225,194,134));
    }//GEN-LAST:event_BuscarFechaVentaMouseEntered

    private void BuscarFechaVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarFechaVentaMouseExited
        BuscarFechaVenta.setBackground(new Color(188,146,100));
    }//GEN-LAST:event_BuscarFechaVentaMouseExited

    private void LimpiarBusquedaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarBusquedaMouseEntered
        LimpiarBusqueda.setBackground(new Color(225,194,134));
    }//GEN-LAST:event_LimpiarBusquedaMouseEntered

    private void LimpiarBusquedaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarBusquedaMouseExited
        LimpiarBusqueda.setBackground(new Color(188,146,100));
    }//GEN-LAST:event_LimpiarBusquedaMouseExited

    private void CLeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLeliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLeliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU_EMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscProducto2;
    private javax.swing.JLabel BuscProducto3;
    private javax.swing.JLabel BuscProducto4;
    public javax.swing.JButton BuscarCL;
    public javax.swing.JButton BuscarFechaVenta;
    public javax.swing.JButton BuscarPR;
    public javax.swing.JButton CLagregar;
    public javax.swing.JTextField CLapellidos;
    public javax.swing.JTextField CLbuscador;
    public javax.swing.JTextField CLdni;
    public javax.swing.JButton CLeditar;
    public javax.swing.JButton CLeliminar;
    public javax.swing.JButton CLguardar;
    public javax.swing.JTextField CLnombre;
    public javax.swing.JLabel CodUsuario;
    private javax.swing.JPanel EmpClientes;
    private javax.swing.JPanel EmpEmpresa;
    private javax.swing.JPanel EmpNuevaVenta;
    private javax.swing.JPanel EmpProductos;
    private javax.swing.JPanel EmpVentas;
    public com.toedter.calendar.JDateChooser JCalendar;
    private javax.swing.JLabel LabelExit;
    public javax.swing.JButton LimpiarBusqueda;
    private javax.swing.JTabbedPane Menu2;
    private javax.swing.JPanel MenuCLIENTES;
    private javax.swing.JPanel MenuEMPRESA;
    private javax.swing.JPanel MenuNUEVAVENTA;
    private javax.swing.JPanel MenuPRODUCTOS;
    private javax.swing.JPanel MenuREPORTEVENTAS;
    public javax.swing.JButton NVagregar;
    public javax.swing.JButton NVbuscarCL;
    public javax.swing.JButton NVbuscarPR;
    public javax.swing.JButton NVcancelar;
    public javax.swing.JTextField NVcantidad;
    public javax.swing.JTextField NVcodigo;
    public javax.swing.JTextField NVdescripcion;
    public javax.swing.JTextField NVdni;
    public javax.swing.JButton NVeliminar;
    public javax.swing.JButton NVguardar;
    public javax.swing.JTextField NVigv;
    public javax.swing.JTextField NVnombre;
    public javax.swing.JTextField NVprecio;
    public javax.swing.JTextField NVstock;
    public javax.swing.JTextField NVsubtotal;
    public javax.swing.JTextField NVtotal;
    public javax.swing.JLabel NombreUsuario;
    public javax.swing.JButton PDFventas;
    public javax.swing.JTextField PRbuscador;
    public javax.swing.JButton ReporteExcelCL;
    public javax.swing.JButton ReporteExcelVENTAS;
    private javax.swing.JLabel btnMinimizar;
    public javax.swing.JLabel direccionEmpresa;
    public javax.swing.JButton eliminarBuscarCL;
    public javax.swing.JButton eliminarBuscarPR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTable jtblCL;
    public javax.swing.JTable jtblNV;
    public javax.swing.JTable jtblPR;
    public javax.swing.JTable jtblVENTAS;
    public javax.swing.JLabel nombreEmpresa;
    public javax.swing.JLabel razonEmpresa;
    public javax.swing.JLabel rucEmpresa;
    public javax.swing.JLabel telefonoEmpresa;
    // End of variables declaration//GEN-END:variables


}
